services:
  db:
    image: mysql:8.3.0
    ports:
      - "3324:3306"
    environment:
      MYSQL_DATABASE: chess_training
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_PASSWORD: password
    volumes:
      - ./tmp/db/mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    restart: always
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true # for biding.pry
    tty: true # for biding.pry
    volumes:
      - .:/tools
    ports:
      - "3024:3000"
    depends_on:
      - db