version: "3.9"
services:
  db:
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: chess_training
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_PASSWORD: password
    volumes:
      - ./tmp/db/mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    restart: always
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && RAILS_ENV=production bundle exec rails assets:precompile && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/tools
    # ports:
    #   - "3089:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
  nginx:
    container_name: mini_games_nginx
    build: docker/nginx/
    volumes:
      - ./run/:/var/run/